// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTH36_xWwnqZK_5tBJYWCmXXdntJOotSs',
    appId: '1:2973195032:web:96bf700d8078c7e0869c6d',
    messagingSenderId: '2973195032',
    projectId: 'mynotes-73cbe',
    authDomain: 'mynotes-73cbe.firebaseapp.com',
    storageBucket: 'mynotes-73cbe.firebasestorage.app',
    measurementId: 'G-QZ1GMG3X5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQLTn32xvev_sZsitMJc7__pfBlxauv18',
    appId: '1:2973195032:android:fa3ba8d91ca10fde869c6d',
    messagingSenderId: '2973195032',
    projectId: 'mynotes-73cbe',
    storageBucket: 'mynotes-73cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCll1K4fa_q2ocVWVkBvCeDJgJixKkR6VM',
    appId: '1:2973195032:ios:3d4941a3bd601eea869c6d',
    messagingSenderId: '2973195032',
    projectId: 'mynotes-73cbe',
    storageBucket: 'mynotes-73cbe.firebasestorage.app',
    iosBundleId: 'com.ahmed.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCll1K4fa_q2ocVWVkBvCeDJgJixKkR6VM',
    appId: '1:2973195032:ios:3d4941a3bd601eea869c6d',
    messagingSenderId: '2973195032',
    projectId: 'mynotes-73cbe',
    storageBucket: 'mynotes-73cbe.firebasestorage.app',
    iosBundleId: 'com.ahmed.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTH36_xWwnqZK_5tBJYWCmXXdntJOotSs',
    appId: '1:2973195032:web:93800ebbcb0bdc5c869c6d',
    messagingSenderId: '2973195032',
    projectId: 'mynotes-73cbe',
    authDomain: 'mynotes-73cbe.firebaseapp.com',
    storageBucket: 'mynotes-73cbe.firebasestorage.app',
    measurementId: 'G-K9L0KBVVVL',
  );
}
